---
title: "Quiz 1"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



 
## Nonexperimental Research Designs

### question 1

 Look at the scatter plot of variables \texttt{x} and \texttt{y}. Which of the following statements is __true__ about the association between these variables?
 
  [insert figure of corrplot]
   
   
* A. There is no evidence of a correlation between `x` and `y`
* B. The correlation between `x` and `y` is very close to 1.00.
* C. There is a moderately strong positive correlation between `x` and `y`.
* D. There is a moderately strong negative correlation between `x` and `y`.

### question 2

Which of the following is **true** of measures of central tendency?

* A. The mean is reliable and stable for skewed distributions
* B. The median allows for more advanced inferential statistics
* C. The median is usually best for normal distributions
* D. The median is preferred over the mean when there are extreme scores in the distribution

## Experimental Research Designs

### question 3

 A researcher wants to determine if a new treatment is effective for reducing Ebola related fever.
  What type of study would potentially provide the strongest evidence that the treatment does indeed cause improvement in Ebola patients?

* A. Randomly assign Ebola patients to one of two groups, either the treatment or placebo group, and then compare the fever of the two groups.
* B. Identify Ebola patients who have received the new treatment and those who did not, and then compare the fever of those two groups.
* C. Identify clusters of villages and then stratify them by gender and compare the fevers of male and female groups.
* D. Both studies (a) and (b) are equally valid methods to establish that the treatment does indeed cause improvement with regards to fever in Ebola patients.


# Short Answer

Read the abstract below and answer the following questions.

 Smoking cessation interventions for cardiac patients need improvement given their weak effects on long-term abstinence rates and low compliance by nurses to implementation.
This study tested the effectiveness of a smoking cessation intervention against usual care in cardiac patients.
 An experimental study was conducted from 2009 to 2012 for which Dutch cardiac patient smokers were randomly assigned to usual care (UC; n = 245) or face-to-face counseling (FC; n = 157).
 The two groups were comparable at baseline and had smoked on average 21 cigarettes a day before hospitalization.
 After six months, interviews occurred to assess self-reported smoking status, measured by the number of cigarettes smoked in the previous month.
 Patients in the FC group had significantly higher smoking abstinence rates than patients in the UC group (p $\leq$ 0.05 at all times).
 These findings suggest that intensive counseling is effective in increasing short-term abstinence rates.

### Question 1:

 1. What is the dependent variable? 
 2. What is the independent variable?
 3. Is there a manipulated variable in this scenario?


 



### Question 2:

 A small class gets the following scores on a test (50, 10, 30, 20, 50, 45, 40, 50, 45, 60).

* 1. What is the mean score on the test?
* 2. What is the mode score on the test? 
* 3. What is range of scores on the test? 
* 4. What is the median score on the test? 

